// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <div
//           className="min-h-screen bg-gray-900 text-gray-100 font-sans"
//           style={{ fontFamily: "Inter, sans-serif" }}
//         >
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "GWAG - Secure Web3 Vault",
  description: "GWAG is a secure Web3 vault for managing your digital assets, wallets, and credentials with advanced security features.",
  keywords: ["web3", "vault", "crypto", "wallet", "security", "blockchain"],
  authors: [{ name: "GWAG Team" }],
  creator: "GWAG",
  publisher: "GWAG",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/logo.svg" />
        <link rel="shortcut icon" href="/logo.svg" type="image/svg+xml" />
        <meta name="theme-color" content="#3B82F6" />
      </head>
      <body className="antialiased">
        <div
          className="min-h-screen bg-gray-900 text-gray-100 font-sans"
          style={{ fontFamily: "Inter, sans-serif" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}