import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div
          className="min-h-screen bg-gray-900 text-gray-100 font-sans"
          style={{ fontFamily: "Inter, sans-serif" }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}